name: docker
 
on:
 push:
   branches: [master]
 
jobs:
 registry-cache:
   runs-on: ubuntu-latest
   steps:
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     -
       name: Login to DockerHub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - uses: actions/checkout@v2
     -
       name: Build and push logproxy-filter-drop
       uses: docker/build-push-action@v5
       with:
         context: ./logproxy-filter-drop
         file: ./logproxy-filter-drop/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipssoftware/logproxy-filter-drop:latest
     -
       name: Build and push logproxy-filter-email
       uses: docker/build-push-action@v5
       with:
         context: ./logproxy-filter-email
         file: ./logproxy-filter-email/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipssoftware/logproxy-filter-email:latest
     -
       name: Build and push logproxy-filter-replace
       uses: docker/build-push-action@v5
       with:
         context: ./logproxy-filter-replace
         file: ./logproxy-filter-replace/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipssoftware/logproxy-filter-replace:latest
     -
       name: Build and push logproxy-filter-test
       uses: docker/build-push-action@v5
       with:
         context: ./logproxy-filter-test
         file: ./logproxy-filter-test/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipssoftware/logproxy-filter-test:latest
